### ISSUE TITLE
关于DateSegmentView疑问

### ISSUE THREAD

**Issue by chundev** [YQqiang/DateSegmentView#1]
您好，在您的项目中有看到            self.datePickerView.subviews.first?.subviews.first?.subviews[0].isHidden = false
 这样的代码。同样的写法。剥离出本项目，没有成功。log了self.datePickerView.subviews.first?.subviews.first?.subviews 这个视图集合 [<UIPickerColumnView: 0x7fdb534b9b30; frame = (0 0; 414 240); autoresize = W+TM+H; gestureRecognizers = <NSArray: 0x600000e445a0>; layer = <CALayer: 0x6000000008a0>>, <UIPickerColumnView: 0x7fdb53565da0; frame = (100 0; 414 240); autoresize = W+TM+H; gestureRecognizers = <NSArray: 0x600000e4a0d0>; layer = <CALayer: 0x60000001c880>>, <UIPickerColumnView: 0x7fdb50f7cfa0; frame = (0 0; 414 240); hidden = YES; autoresize = W+TM+H; gestureRecognizers = <NSArray: 0x600000e46190>; layer = <CALayer: 0x6000001fbd60>>]结果里我有看到 UIPickerColumnView 的 hidden = YES但是UI上并没有体现出来。希望得到回复。

**Comment by YQqiang** [comment]
hi，您好：
&nbsp; &nbsp; &nbsp; demo 写的太久了，实现的有点粗糙，也没做过充分测试，建议用其他成熟库替换；
&nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; 刚刚我把demo进行了更新，支持了 Swift 4.2，您可以更新代码后继续调试；https://github.com/YQqiang/DateSegmentView


&nbsp; &nbsp; &nbsp; 如果仍有问题，您也可以把您的 demo 打包给我，及发生问题的手机型号和系统版本告诉我，我这边也进行调试下。


&nbsp; &nbsp; &nbsp; 感谢您的反馈，如还有其他问题，随时联系。


&nbsp; &nbsp; &nbsp; 谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chundev"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月24日(星期天) 晚上9:28
收件人:&nbsp;"YQqiang/DateSegmentView"<DateSegmentView@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[YQqiang/DateSegmentView] 关于DateSegmentView疑问 (#1)





 
您好，在您的项目中有看到            self.datePickerView.subviews.first?.subviews.first?.subviews[0].isHidden = false
 这样的代码。同样的写法。剥离出本项目，没有成功。log了self.datePickerView.subviews.first?.subviews.first?.subviews 这个视图集合 [<UIPickerColumnView: 0x7fdb534b9b30; frame = (0 0; 414 240); autoresize = W+TM+H; gestureRecognizers = <NSArray: 0x600000e445a0&gt;; layer = <CALayer: 0x6000000008a0&gt;&gt;, <UIPickerColumnView: 0x7fdb53565da0; frame = (100 0; 414 240); autoresize = W+TM+H; gestureRecognizers = <NSArray: 0x600000e4a0d0&gt;; layer = <CALayer: 0x60000001c880&gt;&gt;, <UIPickerColumnView: 0x7fdb50f7cfa0; frame = (0 0; 414 240); hidden = YES; autoresize = W+TM+H; gestureRecognizers = <NSArray: 0x600000e46190&gt;; layer = <CALayer: 0x6000001fbd60&gt;&gt;]结果里我有看到 UIPickerColumnView 的 hidden = YES但是UI上并没有体现出来。希望得到回复。

**Comment by chundev** [comment]
@YQqiang 感谢您的及时回复。您的代码，是没有问题。可以修改成功。我新建了项目。单独运行。self.datePickerView.subviews.first?.subviews.first?.subviews[0].isHidden = false 达到了隐藏的效果。我的问题在非主线程。调用了以上代码段，没有生效。回到主线程执行上述操作。完美解决。
